apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml

namespace: registration

configMapGenerator:
- files:
  - config/application.properties

  name: logdevops-login-backend

commonLabels:
  env: qa

images:
- name: logsdevops/logdevops-pr
  newName: logsdevops/logdevops-pr
  newTag: 1.0.0-SNAPSHOT
