apiVersion: v1
kind: Service
metadata:
  name: logdevops-login-backend
  namespace: registration
spec:
  type: NodePort
  selector:
    app: logdevops-login-backend
  ports:
  - port: 9020
    targetPort: 9020
